title: Agata Dondzik
email: agata@agatdondzik.com
description: I am an Interaction Designer based in Seattle, WA with over 6 years of experience in the industry providing creative direction and digital solutions for mobile and web. I’m passionate about shaping products and services that help people focus on what they do best - be human.
baseurl: ""
path: ""
url:  "https://agatadondzik.com"

dribble_username:  agatadondzik
behance_username:  agatadondzik
twitter_username: agatadondzik
linkedin_username: agatadondzik
flickr_username:  agatadondzik
instagram_username:  agatadondzik

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

sass:
  sass_dir: css
  style:    expanded

exclude:
  - README.md

google_analytics: UA-49263151-1

safe: true

lsi: false

